### ISSUE TITLE
list_languages stumbles over deprecated pygments lexer

### ISSUE THREAD

**Issue by mweinelt** [supakeen/pinnwand#110]
The `utility.list_languages` function gets stuck when `lexer = ('JSONBareObject', (), (), ())`.

The lexer was deprecated in Pygments 2.8.3. 

https://github.com/pygments/pygments/commit/5ee17542490939859843362c9d8047290b284ed1

```pytb
ERROR    tornado.application:web.py:1789 Uncaught exception GET /json/lexers (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:38695', method='GET', uri='/json/lexers', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/nix/store/3wj047kdlgj15gqrgjypid738h7adyxz-python3.8-tornado-6.1/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/build/source/pinnwand/handler/api_deprecated.py", line 188, in get
    self.write(utility.list_languages())
  File "/build/source/pinnwand/utility.py", line 25, in list_languages
    lexers = {lexer[1][0]: lexer[0] for lexer in get_all_lexers()}
  File "/build/source/pinnwand/utility.py", line 25, in <dictcomp>
    lexers = {lexer[1][0]: lexer[0] for lexer in get_all_lexers()}
IndexError: tuple index out of range
ERROR    tornado.access:web.py:2239 500 GET /json/lexers (127.0.0.1) 4.92ms
``

**Comment by mweinelt** [comment]
Fixed in https://github.com/supakeen/pinnwand/commit/b9e72abb7f25104f5e57248294ed9ae1dbc87240, but unreleased.
